allowBuilds:
  "@parcel/watcher": true
  "@playwright/browser-chromium": true
  "@swc/core": true
  better-sqlite3: true
  esbuild: true
  onnxruntime-node: true
  protobufjs: true
  sharp: true
  simple-git-hooks: true
  vue-demi: true

packages:
  - "scripts/*"
  - "packages/*"

patchedDependencies:
  emf-converter@2.0.2: patches/emf-converter@2.0.2.patch
