# 参考资料
# https://github.com/marketplace/actions/vercel-action
# https://vercel.com/guides/how-can-i-use-github-actions-with-vercel

name: Vercel Preview Deployment
env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
on:
  push:
    branches:
      - test
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: show VERCEL_TOKEN
        run: echo -n "${{ secrets.VERCEL_TOKEN }}" | xxd -ps

      - uses: actions/checkout@v2
      - uses: amondnet/vercel-action@v25.1.1
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }} # Required
          vercel-org-id: ${{ secrets.ORG_ID}} #Required
          vercel-project-id: ${{ secrets.PROJECT_ID}} #Required
          working-directory: ./packages/test
          alias-domains: small-alice-web-dev.ruancat6312.top
